# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install installer
      run: |
        pip install pyinstaller
    - name: Build the application
      run: |
        Move-Item win7\mdt_control.py mdt_control.py -force
        Move-Item win7\mdt_deck_reader.py mdt_deck_reader.py -force
        pyinstaller -F mdt_gui.py -p mdt_service.py -p mdt.py -p mdt_deck_reader.py -p mdt_control.py -p mdt_cv.py -n mdt_cv -n mdt -i controller.ico --distpath mdt --noconsole --uac-admin
        Move-Item LICENSE mdt
        Move-Item data mdt
        Move-Item locales mdt
        Move-Item README.md mdt
        Move-Item config.ini mdt
    - uses: actions/upload-artifact@v2
      with:
        name: mdt_nightly_win7
        path: mdt
